# Oracle database connection placeholders for teaching/demo setup
spring.datasource.url=jdbc:oracle:thin:@//192.168.56.101:1521/pdborcl
spring.datasource.username=ordermgmt735
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Helpful during development
spring.sql.init.mode=never
server.port=8080
